require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'db/schema.rb'
    - 'tmp/**/*'
    - '**/*.haml'
    - 'bin/**/*'


Rails/FilePath:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*.rb'

Metrics/ModuleLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'config/routes.rb'
    - 'test/factories/*.rb'
    - app/views/**/*.xlsx.axlsx

Metrics/PerceivedComplexity:
  Max: 10

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Rails/SkipsModelValidations:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Rails/NotNullColumn:
  Exclude:
  - 'db/migrate/*.rb'
