version: '3'

services:
  db:
    image: postgres:10.6
    container_name: misha_db
  web:
    build: .
    image: misha/web
    container_name: misha-web
    command: bash -c "puma"
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - /app/node_modules
